# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test if MAC address strings are in canonical form
#'
#' The canonical form for MAC addresses strings is 6, 2-character
#' octets separated by colons. This function returns `TRUE` if
#' an address string is in canonical format.
#'
#' @md
#' @param mac character vector of MAC address strings
#' @export
#' @examples
#' is_canonical_mac("c8:69:cd:28:5a:7d")
is_canonical_mac <- function(mac) {
    .Call('_MACtools_is_canonical_mac', PACKAGE = 'MACtools', mac)
}

#' Convert a charactrer vector of MAC addresses to
#' a `list` of `raw` vectors.
#'
#' @md
#' @param mac character vector of MAC address strings
#' @export
#' @examples
#' as_raw_mac("c8:69:cd:28:5a:7d")
as_raw_mac <- function(mac) {
    .Call('_MACtools_as_raw_mac', PACKAGE = 'MACtools', mac)
}

#' Converts a character vector of MAC addresses into canonical form
#'
#' The canonical form for MAC addresses strings is 6, 2-character
#' octets separated by colons. This function returns `TRUE` if
#' an address string is in canonical format.
#'
#' @md
#' @param mac character vector of MAC address strings
#' @export
#' @examples
#' canonicalize_mac("b8:e8:56:35:36:4")
canonicalize_mac <- function(mac) {
    .Call('_MACtools_canonicalize_mac', PACKAGE = 'MACtools', mac)
}

